### ISSUE TITLE
fc_run.py: not found in E. coli example

### ISSUE THREAD

**Issue by ishengtsai** [PacificBiosciences/FALCON#200]
Hi, I successfully installed  FALCON v0.3 and tried to run the E. coli example, but could not find the fc_run.py. Could someone check please? The example setup seems the same as my current data setup (9 cells) and it would be great if I can get it running first. Log file attached below. 

Best,
Jason

make run-ecoli

.
.
.
symlink: 'run/ecoli/data/ecoli.1.subreads.fasta'
symlink: 'run/ecoli/data/ecoli.2.subreads.fasta'
symlink: 'run/ecoli/data/ecoli.3.subreads.fasta'
cd run/ecoli; fc_run.py fc_run.cfg logging.ini
/bin/sh: 1: fc_run.py: not found
make: *** [run-ecoli] Error 127

**Comment by pb-jchin** [comment]
please use 0.4.0, the missing file is fixed https://github.com/PacificBiosciences/FALCON-integrate/tree/0.4.0

**Comment by ishengtsai** [comment]
Hi Jason,

The file is still missing. Please suggest if I've done something wrong.

Best, Jason


git clone https://github.com/PacificBiosciences/FALCON-integrate.git
cd FALCON-integrate
git checkout 0.4.0
make init
make virtualenv
make check
make -j install
make test
make run-ecoli


symlink: 'run/ecoli/data/ecoli.1.subreads.fasta'
symlink: 'run/ecoli/data/ecoli.2.subreads.fasta'
symlink: 'run/ecoli/data/ecoli.3.subreads.fasta'
cd run/ecoli; fc_run.py fc_run.cfg logging.ini
/bin/sh: 1: fc_run.py: not found
make: *** [run-ecoli] Error 127

**Comment by pb-jchin** [comment]
do you use git 2.*? 
please run `git submodule` to make sure the dependents are the right revision.

```
$ git submodule
 1ee01a199d4b04ba7b4c5d1dd8c5f869c5a86dce DALIGNER (remotes/origin/gm-master-21-g1ee01a1)
 88e30590eae130ee899c52e69f72a887c3a10026 DAZZ_DB (remotes/origin/gm-master-8-g88e3059)
 49f0885cfcaf4aef10aa84a39dd7809aa8eb7068 FALCON (0.2JASM-244-g49f0885)
 97aecd0a69f62e3029bd5fd233ff9cceccd42bce FALCON-examples (remotes/origin/lambda-31-g97aecd0)
 215e8cfcdda412258daff3b689cc7d0daeca4e47 FALCON-make (remotes/origin/pype)
 483836854e1bafb6e40cf17f3a9382efe351daad git-sym (heads/master)
 a6751fac8aa575b130c558488af0532f47cf8999 pypeFLOW (v0.1.0-42-ga6751fa)
 8e9cb4a7c34a12762a0ef8b2c5003ded4346cd49 virtualenv (heads/develop)
```

**Comment by ishengtsai** [comment]
Hi Jason,

Yes. I used git version 2.5.3 and I think I have all the latest version of FALCON. Please see the commands I used below and result of git submodule.

git clone git://github.com/PacificBiosciences/FALCON-integrate.git
cd FALCON-integrate
git checkout 0.4.0
git submodule update --init
make init
make virtualenv
make check
make -j install
make test
cd /home/ijt/bin/FALCON-integrate/FALCON-examples/
make run-ecoli


cd run/ecoli; fc_run.py fc_run.cfg logging.ini
/bin/sh: 1: fc_run.py: not found
make: *** [run-ecoli] Error 127

![image](https://cloud.githubusercontent.com/assets/5182142/9980172/fd6d2176-5fc0-11e5-9a2c-b0e131aa175f.png)

**Comment by pb-cdunn** [comment]
**FALCON-integrate** is intended to prove that everything *can* work, but there is no universally ideal way to install software. That's up to you.

We see that `make test` passed, which means you are very close. Your next step was this:

    cd /home/ijt/bin/FALCON-integrate/FALCON-examples/
    make run-ecoli

Everything in **FALCON-examples** assumes that `fc_run.py` is available on your `$PATH`. If you want to use `fc_run.py` from your shell after you have set-up a virtualenv via **FALCON-integrate**/**FALCON-make**, then one way (my personal favorite) is to do this in your shell:

    . FALCON-integrate/fc_env/bin/activate

If you wonder why `make test` worked, look at  `FALCON-integrate/makefile`, which activates your virtualenv in a sub-shell in a tricky way (the `%:` rule). Some people have had problems with **virtualenv**, so we absolutely do *not* require **virtualenv** when using **FALCON**. It's just what we use for our integration-testing.

**Comment by ishengtsai** [comment]
Thanks. It's now solved and I've managed to produce an initial assembly from ecoli test and my own data. Now moving onto 16 cells...
